TARGET = arrayAssignment arrayCompare arrayPointer bubble charAdress charGetPut charPointerOperation
         dynamicAllocation endian enumExample fflushEx fileDescriptor filePointer functionPointer
         getSeries helloStr pointer2 pointerConcept putSeries qsort selection stringExample sumArrayFunction
		 sumMatrixFunction sumMatrixFunction2 swap swapFunction unionExample voidPointer.
 
all : ${TARGET}
arrayAssignment : $@
arrayCompare : $@
arrayPointer : $@
bubble : $@
charAdress : $@
charGetPut : $@
charPointerOperation : $@
dynamicAllocation : $@
endian: $@
enumExample : $@
fflushEx : $@
fileDescriptor : $@
filePointer : $@
functionPointer : $@
getSeries : $@
helloStr : $@
pointer2 : $@
pointerConcept : $@
putSeries : $@
qsort : $@
selection : $@
stringExample : $@
sumArrayFunction : $@
sumMatrixFunction : $@
sumMatrixFunction2 : $@
swap : $@
swapFunction : $@
unionExample : $@
voidPointer : $@

 clean :
	rm ${TARGET} 