TARGET = absolute ascii average2022Temp baseball bigLetter dice findMax findValueinArray functionSum grade grade2
         leafYear multiplyTable one2Ten one2TenDoWhile one2TenSum one2TenWhile passFail posZeroNeg 
          power procScore randomTwoInt returnValue scoreGrade star staticLocalVariable sumArray sumMatrix
all : ${TARGET}
absolute : $@
ascii : $@
average2022Temp : $@
baseball : $@
bigLetter : $@
dice : $@
findMax : $@
findValueinArray : $@
functionSum : $@
grade : $@
grade2 : $@
leafYear : $@
multiplyTable : $@
one2Ten : $@
one2TenDoWhile : $@
one2TenSum : $@
one2TenWhile : $@
passFail : $@
posZeroNeg : $@
power : $@
procScore : $@
randomTwoInt : $@
returnValue : $@
scoreGrade : $@
star : $@
staticLocalVariable : $@
sumArray : $@
sumMatrix : $@
temp2022.dat : $@
clean :
	rm ${TARGET} 